using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

public class GameManager : MonoBehaviour
{
    public Transform player;
    public static Transform Player { get { if (instance == null) { return null; } return instance.player; } }

    public static GameManager instance { get;private set; }

    public GameObject gameOverPanel;
    void Awake()
    {
        instance = this;
    }
    public static void GameOver()
    {
        instance.gameOverPanel.SetActive(true);


    }

    public void Restart()
    {
        SceneManager.LoadScene(0);
    }
}
